// Book details (Sample data - You can fetch this from a database)
const books = {
   "1": {
       "title": "REHBAR-E-KULLIYAT-E-UMOOR-E-TABIYAH",
       "author": "SYED AFZAL HUSSAIN",
       "image": "booksection/kulliyateumooretabiya.jpg",
       "binding": "Paperback",
       "pages": "185",
       "edition": "1st Edition",
       "mrp": "796",
       "discount": "700",
       "amazon": "https://amzn.in/d/book1",
       "flipkart": "https://www.flipkart.com/book1",
       "meesho": "https://www.meesho.com/book1"
   },
   "2": {
       "title": "CONCISE HISTORY & ETHICS OF MEDICINE",
       "author": "SYED AFZAL HUSSAIN",
       "image": "booksection/concisehistory.jpg",
       "binding": "Paperback",
       "pages": "856",
       "edition": "1st Edition",
       "mrp": "164",
       "discount": "600",
       "amazon": "https://amzn.in/d/book2",
       "flipkart": "https://www.flipkart.com/book2",
       "meesho": "https://www.meesho.com/book2"
   },
   "3": {
       "title": "REHBAR MANTIQ WA FALSAFA",
       "author": "SYED AFZAL HUSSAIN",
       "image": "booksection/rehbarmantiq.jpg",
       "binding": "Paperback",
       "pages": "842",
       "edition": "1st Edition",
       "mrp": "976",
       "discount": "500",
       "amazon": "https://amzn.in/d/book3",
       "flipkart": "https://www.flipkart.com/book3",
       "meesho": "https://www.meesho.com/book3"
   },
   "4": {
       "title": "TARIKH-E-TIBB WA AKHLAKIYAT",
       "author": "SYED AFZAL HUSSAIN",
       "image": "booksection/tareekhetibb.jpg",
       "binding": "Paperback",
       "pages": "251",
       "edition": "1st Edition",
       "mrp": "446",
       "discount": "400",
       "amazon": "https://amzn.in/d/book4",
       "flipkart": "https://www.flipkart.com/book4",
       "meesho": "https://www.meesho.com/book4"
   },
   "5": {
       "title": "AFZAL UL MUFREDAT (VOL:1-4)",
       "author": "SYED ASAD HUSSAIN",
       "image": "booksection/afzalulmufredat.jpg",
       "binding": "Paperback",
       "pages": "374",
       "edition": "1st Edition",
       "mrp": "899",
       "discount": "300",
       "amazon": "https://amzn.in/d/book5",
       "flipkart": "https://www.flipkart.com/book5",
       "meesho": "https://www.meesho.com/book5"
   },
   "6": {
       "title": "REHBAR KULLIYAT-E-ADVIA",
       "author": "SYED AFZAL HUSSAIN",
       "image": "booksection/kulliyateadvia.jpg",
       "binding": "Paperback",
       "pages": "66",
       "edition": "1st Edition",
       "mrp": "645",
       "discount": "200",
       "amazon": "https://amzn.in/d/book6",
       "flipkart": "https://www.flipkart.com/book6",
       "meesho": "https://www.meesho.com/book6"
   },
   "7": {
       "title": "REHBAR-E-USOOLE ILAJ WA NUSKHA NAVESI",
       "author": "SYED AFZAL HUSSAIN",
       "image": "booksection/usooleilaj.jpg",
       "binding": "Paperback",
       "pages": "120",
       "edition": "1st Edition",
       "mrp": "654",
       "discount": "100",
       "amazon": "https://amzn.in/d/book7",
       "flipkart": "https://www.flipkart.com/book7",
       "meesho": "https://www.meesho.com/book7"
   },
   "8": {
       "title": "INTEKHAB-E-MAZAMEEN",
       "author": "DR. JAVED",
       "image": "booksection/intekhabemazameen.jpg",
       "binding": "Paperback",
       "pages": "157",
       "edition": "1st Edition",
       "mrp": "498",
       "discount": "900",
       "amazon": "https://amzn.in/d/book8",
       "flipkart": "https://www.flipkart.com/book8",
       "meesho": "https://www.meesho.com/book8"
   },
   "9": {
       "title": "MAHIYATUL AMRAZ NIZAMI",
       "author": "DR. SABA",
       "image": "booksection/mahiyatul amraz nizami.jpg",
       "binding": "Paperback",
       "pages": "230",
       "edition": "1st Edition",
       "mrp": "654",
       "discount": "800",
       "amazon": "https://amzn.in/d/book9",
       "flipkart": "https://www.flipkart.com/book9",
       "meesho": "https://www.meesho.com/book9"
   },
   "10": {
       "title": "ILMUL SAIDLA",
       "author": "SYED AFZAL HUSSAIN",
       "image": "booksection/ilmulsaidla.jpg",
       "binding": "Paperback",
       "pages": "249",
       "edition": "1st Edition",
       "mrp": "989",
       "discount": "700",
       "amazon": "https://amzn.in/d/book9",
       "flipkart": "https://www.flipkart.com/book9",
       "meesho": "https://www.meesho.com/book9"
   },
   "11": {
       "title": "KITAB UL MURRAKABAT",
       "author": "SYED AFZAL HUSSAIN",
       "image": "booksection/kitabulmurrakabat.jpg",
       "binding": "Paperback",
       "pages": "961",
       "edition": "1st Edition",
       "mrp": "198",
       "discount": "600",
       "amazon": "https://amzn.in/d/book9",
       "flipkart": "https://www.flipkart.com/book9",
       "meesho": "https://www.meesho.com/book9"
   },
   "12": {
       "title": "QADEEM WA JADEED ILMUL AMRAZ",
       "author": "DR. SIDRA",
       "image": "booksection/ilmulamraz.jpg",
       "binding": "Paperback",
       "pages": "385",
       "edition": "1st Edition",
       "mrp": "673",
       "discount": "500",
       "amazon": "https://amzn.in/d/book9",
       "flipkart": "https://www.flipkart.com/book9",
       "meesho": "https://www.meesho.com/book9"
   },
   "13": {
       "title": "RAPID REVIEW GENERAL PATHOLOGY",
       "author": "DR SANA KAUSER ATEEQUE AHMED",
       "image": "booksection/generalpathology.jpg",
       "binding": "Paperback",
       "pages": "87",
       "edition": "1st Edition",
       "mrp": "319",
       "discount": "400",
       "amazon": "https://amzn.in/d/book9",
       "flipkart": "https://www.flipkart.com/book9",
       "meesho": "https://www.meesho.com/book9"
   },
    "14": {
       title: "RAPID REVIEW MICROBIOLOGY",
       author: "Dr. Sana Kauser",
       image: "booksection/micropathology.jpg",
       binding: "Paperback",
       pages: "987",
       edition: "1st Edition",
       mrp: "974.00",
       discount: "300.00",
       amazon: "https://amzn.in/d/cGanong",
       flipkart: "https://www.flipkart.com/ganong",
       meesho: "https://www.meesho.com/ganong"
   },
   "15": {
       title: "RAPID REVIEW SYSTEMIC PATHOLOGY",
       author: "Dr. Saba Nazli",
       image: "booksection/systemicpathology.jpg",
       binding: "Paperback",
       pages: "21",
       edition: "1st Edition",
       mrp: "971.00",
       discount: "200.00",
       amazon: "https://amzn.in/d/cDavidson",
       flipkart: "https://www.flipkart.com/davidson",
       meesho: "https://www.meesho.com/davidson"
   },
   
};
