# Generated by Django 6.0 on 2026-02-01 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_book_options_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('UG', 'UG Syllabus'), ('PG', 'PG Syllabus'), ('PRE-TIB', 'Pre-Tib Syllabus')], max_length=20)),
                ('semester', models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester'), ('3-6', 'Third to Sixth Semester'), ('OTHER', 'General / Other')], default='OTHER', max_length=20)),
                ('pdf_file', models.FileField(upload_to='syllabus_pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'semester', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='mrp_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.book'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['price'], name='store_book_price_3abd43_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='store_order_created_4ba192_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_paid'], name='store_order_is_paid_140bc1_idx'),
        ),
    ]
