# Generated by Django 6.0 on 2026-02-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_bundle_cartbundleitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishWithUsSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('author_name', models.CharField(max_length=200)),
                ('position_affiliation', models.CharField(blank=True, max_length=200)),
                ('mailing_address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('topic_definition', models.TextField(blank=True)),
                ('overview', models.TextField(blank=True)),
                ('reasons', models.TextField(blank=True)),
                ('unique_features', models.TextField(blank=True)),
                ('competition', models.TextField(blank=True)),
                ('toc', models.TextField(blank=True)),
                ('pages', models.CharField(blank=True, max_length=50)),
                ('delivery_time', models.CharField(blank=True, max_length=100)),
                ('text_electronic', models.CharField(blank=True, max_length=20)),
                ('text_software', models.CharField(blank=True, max_length=200)),
                ('special_features', models.TextField(blank=True)),
                ('figures_computer', models.CharField(blank=True, max_length=20)),
                ('figures_software', models.CharField(blank=True, max_length=200)),
                ('market', models.TextField(blank=True)),
                ('societies', models.TextField(blank=True)),
                ('journals', models.TextField(blank=True)),
                ('textbook_details', models.TextField(blank=True)),
                ('previous_works', models.TextField(blank=True)),
                ('why_better', models.TextField(blank=True)),
                ('reviewers', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
