# Generated by Django 6.0 on 2026-02-05 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='link',
        ),
        migrations.AddField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='store.category'),
        ),
        migrations.AddField(
            model_name='banner',
            name='mobile_height',
            field=models.PositiveSmallIntegerField(default=240, help_text='Banner height in pixels for mobile screens.'),
        ),
    ]
