# Generated by Django 6.0 on 2026-02-05 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_banner_link_banner_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='cta_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_ctas', to='store.category'),
        ),
        migrations.AddField(
            model_name='banner',
            name='cta_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='banner',
            name='headline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='banner',
            name='subheadline',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='banner',
            name='tablet_height',
            field=models.PositiveSmallIntegerField(default=300, help_text='Banner height in pixels for tablet screens.'),
        ),
    ]
