# Generated by Django 6.0 on 2026-02-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_search_audit_address_pricing_and_flags'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='store_audit_action_1ee354_idx',
            old_name='store_audi_action_ba4b6f_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='store_audit_created_892a00_idx',
            old_name='store_audi_created_1edc8e_idx',
        ),
        migrations.RenameIndex(
            model_name='searchquerylog',
            new_name='store_searc_created_db27a8_idx',
            old_name='store_searc_created_3c2f66_idx',
        ),
        migrations.RenameIndex(
            model_name='searchquerylog',
            new_name='store_searc_results_5d1853_idx',
            old_name='store_searc_results_7d0c11_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
