# Generated by Codex
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0025_order_payment_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="show_on_mobile",
            field=models.BooleanField(default=False, help_text="Enable this banner for mobile screens."),
        ),
        migrations.AddField(
            model_name="banner",
            name="show_on_desktop",
            field=models.BooleanField(default=True, help_text="Enable this banner for desktop/tablet screens."),
        ),
    ]
