# Generated by Django 6.0 on 2026-02-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_banner_device_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='show_on_mobile',
            field=models.BooleanField(default=True, help_text='Enable this banner for mobile screens.'),
        ),
    ]
