# Generated by Django 6.0 on 2026-02-11 04:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_banner_show_on_mobile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IKSCoinsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='IKS Coins+', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('program_enabled', models.BooleanField(default=True)),
                ('earn_percentage', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('max_coins_per_order', models.PositiveIntegerField(default=100)),
                ('monthly_earning_cap', models.PositiveIntegerField(default=300)),
                ('redemption_percentage_limit', models.PositiveSmallIntegerField(default=20)),
                ('minimum_cart_value', models.DecimalField(decimal_places=2, default=Decimal('300.00'), max_digits=10)),
                ('credit_delay_days', models.PositiveSmallIntegerField(default=7)),
                ('registration_bonus', models.PositiveIntegerField(default=25)),
                ('first_purchase_bonus', models.PositiveIntegerField(default=25)),
                ('review_bonus', models.PositiveIntegerField(default=10)),
                ('profile_completion_bonus', models.PositiveIntegerField(default=10)),
                ('disallow_with_coupon', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coin_manual_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='coin_release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coin_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='coins_earned_estimate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='coins_earned_final',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='coins_redeemed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='iks_follow_facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='iks_follow_instagram',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='IKSWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('pending_balance', models.PositiveIntegerField(default=0)),
                ('total_earned', models.PositiveIntegerField(default=0)),
                ('total_redeemed', models.PositiveIntegerField(default=0)),
                ('monthly_earned', models.PositiveIntegerField(default=0)),
                ('month_key', models.CharField(default='', help_text='YYYY-MM for monthly cap tracking', max_length=7)),
                ('is_frozen', models.BooleanField(default=False)),
                ('is_earning_blocked', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iks_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='IKSWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('purchase_reward', 'Purchase Reward'), ('registration_bonus', 'Registration Bonus'), ('first_purchase_bonus', 'First Purchase Bonus'), ('review_reward', 'Review Reward'), ('profile_completion_reward', 'Profile Completion Reward'), ('redemption_deduction', 'Redemption Deduction'), ('manual_adjustment', 'Manual Admin Adjustment')], max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('coins', models.IntegerField(help_text='Positive for credit, negative for deduction.')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_transactions', to='store.book')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_transactions', to='store.order')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='store.ikswallet')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'release_date'], name='store_ikswa_status_a86c9e_idx'), models.Index(fields=['tx_type', 'created_at'], name='store_ikswa_tx_type_ae6af0_idx')],
            },
        ),
    ]
