# Generated by Django 6.0 on 2026-02-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_coupon_minimum_order_amount_coupon_valid_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnaniTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=255, unique=True)),
                ('arabic_term', models.CharField(blank=True, db_index=True, max_length=255)),
                ('urdu_term', models.CharField(blank=True, db_index=True, max_length=255)),
                ('english_meaning', models.CharField(db_index=True, max_length=400)),
                ('unani_explanation', models.TextField()),
                ('modern_medical_equivalent', models.CharField(blank=True, db_index=True, max_length=400)),
                ('category', models.CharField(choices=[('disease', 'Disease'), ('drug', 'Drug'), ('anatomy', 'Anatomy'), ('mizaj', 'Mizaj'), ('ilaj', 'Ilaj (Therapy)'), ('qawaid', 'Qawaid (Principles)'), ('other', 'Other')], db_index=True, default='other', max_length=40)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['term'],
                'indexes': [models.Index(fields=['term'], name='store_unani_term_afc983_idx'), models.Index(fields=['category', 'is_published'], name='store_unani_categor_77b204_idx'), models.Index(fields=['is_published', 'created_at'], name='store_unani_is_publ_178f24_idx')],
            },
        ),
    ]
