# Generated by Django 6.0 on 2026-02-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_order_courier_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='system_id',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True, unique=True),
        ),
    ]
