# Generated by Django 6.0 on 2026-02-14 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_book_system_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='readership',
        ),
    ]
