# Generated by Django 6.0 on 2026-02-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_remove_book_readership'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='desktop_crop_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banner',
            name='desktop_crop_width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banner',
            name='desktop_crop_x',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banner',
            name='desktop_crop_y',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banner',
            name='mobile_crop_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banner',
            name='mobile_crop_width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banner',
            name='mobile_crop_x',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banner',
            name='mobile_crop_y',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
