# Generated by Django 6.0 on 2026-04-08 18:00

import django.db.models.deletion
import re
import unicodedata
from django.conf import settings
from django.db import migrations, models


_BIDI_CONTROL_CHARS = "\u200e\u200f\u202a\u202b\u202c\u202d\u202e\u2066\u2067\u2068\u2069\u061c"
_ARABIC_DIACRITICS_RE = re.compile(r"[\u0610-\u061a\u064b-\u065f\u0670\u06d6-\u06ed]")
_WHITESPACE_RE = re.compile(r"\s+")
_NON_ALNUM_SPACE_RE = re.compile(r"[^a-z0-9\s]")
_ARABIC_VARIANT_MAP = str.maketrans(
    {
        "ي": "ی",
        "ى": "ی",
        "ك": "ک",
        "أ": "ا",
        "إ": "ا",
        "آ": "ا",
        "ٱ": "ا",
        "ؤ": "و",
        "ئ": "ی",
        "ة": "ه",
        "ۀ": "ه",
        "ـ": "",
    }
)
_TRANSLIT_APOSTROPHE_MAP = str.maketrans(
    {
        "'": "’",
        "`": "’",
        "‘": "’",
        "ʼ": "’",
        "ʻ": "’",
        "ʹ": "’",
    }
)


def _normalize_script_text(value):
    text = str(value or "").translate(str.maketrans("", "", _BIDI_CONTROL_CHARS))
    text = text.translate(_ARABIC_VARIANT_MAP)
    text = _ARABIC_DIACRITICS_RE.sub("", text)
    text = _WHITESPACE_RE.sub(" ", text).strip()
    return text


def _normalize_translit_text(value):
    text = str(value or "").translate(_TRANSLIT_APOSTROPHE_MAP)
    return _WHITESPACE_RE.sub(" ", text).strip()


def _normalize_latin_search(value):
    text = _normalize_translit_text(value).lower()
    text = unicodedata.normalize("NFKD", text)
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    text = text.replace("ʿ", "").replace("ʾ", "").replace("’", "")
    text = _NON_ALNUM_SPACE_RE.sub(" ", text)
    return _WHITESPACE_RE.sub(" ", text).strip()


def populate_unaniterm_normalized_fields(apps, schema_editor):
    UnaniTerm = apps.get_model("store", "UnaniTerm")
    for term in UnaniTerm.objects.all().iterator():
        cleaned_script = _normalize_script_text(term.arabic_script)
        cleaned_translit = _normalize_translit_text(term.transliteration)
        cleaned_english = _WHITESPACE_RE.sub(" ", str(term.english_term or "")).strip()
        updates = {
            "arabic_script": cleaned_script,
            "transliteration": cleaned_translit,
            "english_term": cleaned_english,
            "arabic_script_normalized": _normalize_script_text(cleaned_script),
            "transliteration_normalized": _normalize_latin_search(cleaned_translit),
            "english_term_normalized": _normalize_latin_search(cleaned_english),
        }
        UnaniTerm.objects.filter(pk=term.pk).update(**updates)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_book_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unaniterm',
            name='arabic_script_normalized',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='unaniterm',
            name='english_term_normalized',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='unaniterm',
            name='transliteration_normalized',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255),
        ),
        migrations.RunPython(populate_unaniterm_normalized_fields, noop_reverse),
        migrations.CreateModel(
            name='UnaniReferenceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('citation', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='store_unani_is_acti_c38297_idx')],
            },
        ),
        migrations.AddField(
            model_name='unaniterm',
            name='reference_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms', to='store.unanireferencesource'),
        ),
        migrations.CreateModel(
            name='DictionaryQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('normalized_query', models.CharField(blank=True, db_index=True, max_length=255)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('section', models.CharField(blank=True, max_length=120)),
                ('letter', models.CharField(blank=True, max_length=8)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='store_dicti_created_a34d99_idx'), models.Index(fields=['results_count'], name='store_dicti_results_ab7fbe_idx'), models.Index(fields=['normalized_query'], name='store_dicti_normali_f09c2d_idx')],
            },
        ),
        migrations.CreateModel(
            name='DictionaryTermOpenLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_logs', to='store.unaniterm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='store_dicti_created_d50dd1_idx'), models.Index(fields=['term', 'created_at'], name='store_dicti_term_id_720d0a_idx')],
            },
        ),
    ]
