# Generated by Django 6.0 on 2026-04-13 11:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_unaniterm_arabic_script_normalized_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTestExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('full_length', 'Full Length'), ('subject', 'Subject Wise'), ('topic', 'Topic Wise'), ('daily', 'Daily Test'), ('adaptive', 'Adaptive'), ('custom', 'Custom')], db_index=True, default='full_length', max_length=20)),
                ('question_count', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_minutes', models.PositiveIntegerField(default=120, validators=[django.core.validators.MinValueValidator(1)])),
                ('marks_per_question', models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=6)),
                ('negative_marking', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('pass_percent', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5)),
                ('language', models.CharField(default='English', max_length=40)),
                ('shuffle_questions', models.BooleanField(default=True)),
                ('shuffle_options', models.BooleanField(default=True)),
                ('show_result_immediately', models.BooleanField(default=True)),
                ('allow_review_mode', models.BooleanField(default=True)),
                ('is_ranked', models.BooleanField(default=False)),
                ('access_level', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MockTestSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MockTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_token', models.CharField(blank=True, db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('auto_submitted', 'Auto Submitted')], db_index=True, default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('attempted_count', models.PositiveIntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('percentile_estimate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('rank_projection', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('integrity_flags', models.JSONField(blank=True, default=dict)),
                ('analytics', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mocktest_attempts', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='store.mocktestexam')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MockTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField()),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explanation_short', models.TextField(blank=True)),
                ('explanation_detailed', models.TextField(blank=True)),
                ('memory_trick', models.TextField(blank=True)),
                ('key_concept', models.CharField(blank=True, max_length=255)),
                ('reference_source', models.CharField(blank=True, max_length=255)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated concept tags.', max_length=400)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='medium', max_length=10)),
                ('is_previous_year', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mocktest_questions_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mocktest_questions_updated', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='store.mocktestsubject')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MockTestMistakeNotebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], db_index=True, default='active', max_length=12)),
                ('error_type', models.CharField(choices=[('wrong', 'Wrong'), ('skipped', 'Skipped')], default='wrong', max_length=10)),
                ('next_revision_on', models.DateField(blank=True, db_index=True, null=True)),
                ('revision_stage', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('latest_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mistake_entries', to='store.mocktestattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mocktest_mistakes', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistake_entries', to='store.mocktestquestion')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MockTestAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.PositiveIntegerField(default=0)),
                ('option_order', models.JSONField(blank=True, default=list)),
                ('selected_option', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('', 'Unanswered')], default='', max_length=1)),
                ('is_marked_for_review', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='store.mocktestattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='store.mocktestquestion')),
            ],
            options={
                'ordering': ['question_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MockTestQuestionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('publish', 'Publish'), ('unpublish', 'Unpublish')], max_length=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='store.mocktestquestion')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MockTestRevisionQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_days', models.PositiveSmallIntegerField(default=1)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('is_done', models.BooleanField(db_index=True, default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_queue_entries', to='store.mocktestquestion')),
                ('source_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_queue_entries', to='store.mocktestattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mocktest_revision_queue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='mocktestexam',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='store.mocktestsubject'),
        ),
        migrations.CreateModel(
            name='MockTestTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='store.mocktestsubject')),
            ],
            options={
                'ordering': ['subject__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='mocktestquestion',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='store.mocktesttopic'),
        ),
        migrations.AddField(
            model_name='mocktestexam',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='store.mocktesttopic'),
        ),
        migrations.AddIndex(
            model_name='mocktestattempt',
            index=models.Index(fields=['status', 'started_at'], name='store_mockt_status_4040ba_idx'),
        ),
        migrations.AddIndex(
            model_name='mocktestattempt',
            index=models.Index(fields=['exam', 'status'], name='store_mockt_exam_id_f44fe8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mocktestmistakenotebook',
            unique_together={('user', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='mocktestattemptanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AddIndex(
            model_name='mocktestrevisionqueue',
            index=models.Index(fields=['user', 'is_done', 'due_at'], name='store_mockt_user_id_33915f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mocktesttopic',
            unique_together={('subject', 'name')},
        ),
        migrations.AddIndex(
            model_name='mocktestquestion',
            index=models.Index(fields=['status', 'is_active'], name='store_mockt_status_b1cead_idx'),
        ),
        migrations.AddIndex(
            model_name='mocktestquestion',
            index=models.Index(fields=['subject', 'topic'], name='store_mockt_subject_5efbda_idx'),
        ),
        migrations.AddIndex(
            model_name='mocktestquestion',
            index=models.Index(fields=['difficulty', 'is_previous_year'], name='store_mockt_difficu_b834d4_idx'),
        ),
    ]
