services:
  - type: web
    name: idara-bookstore
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && gunicorn idara_project.wsgi:application
    autoDeploy: true
