# Generated by Django 6.0 on 2026-01-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_book_is_bestseller_book_is_new_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='mrp_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount', max_digits=10, null=True),
        ),
    ]
